### ISSUE TITLE
Keyboard shortcuts require caps?

### ISSUE THREAD

**Issue by christopherlovell** [WillJRoper/h5forest#1]
The description of the keyboard commands suggest that they require capitalised 'C' but it doesn't seem like this is actually the case. Should this read 'Ctrl'?

**Comment by WillJRoper** [comment]
That's normally shorthand for CTRL. Clearly you're not an emacs user ;) 😂 I'll make that more explicit for now since not everyone has seen the light! I think I'm going to pivot to a leader key model in the long run so the hotkeys can be dynamically hidden and shown and changed given the input keys.

**Comment by christopherlovell** [comment]
you mean you're moving to a vim structure? ;)

**Comment by WillJRoper** [comment]
Well... strictly I'm just using my Doom emacs + evil mode config for inspiration so its franken-vim 😂
